### ISSUE TITLE
Please add B3 to the HUMIDITY_MODELS constant

### ISSUE THREAD

**Issue by marathonfrank** [astrandb/sentio#25]
### Feature request

Thank you very much for your great work. 

I have the B3 model. This B3 model also supports an evaporator and has a humidity sensor.  
Therefore it would be great if you could extend the constant HUMIDITY_MODELS in the file const.py with the model B3.

> HUMIDITY_MODELS = ("B3", "C3", "C3I", "D3", "D3I") 

Thank you very much. 

### What version of the integration are you using?

sentio v0.0.18

**Comment by astrandb** [comment]
Thank you for the feature request. I took a quick look in the documentation and I could not see that any other changes are needed for B3.
